spring.application.name=sb-ecom
spring.h2.console.enabled=true
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/sb-ecom
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jackson.property-naming-strategy=SNAKE_CASE
# project
project.image=./images
# setting
spring.app.jwtSecret=MySecretKey123456789qwertyuiopasdfghjklzxcvbnm1234567
spring.app.jwtExpirationMs=3000000
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG